# Generated by Django 4.2.1 on 2023-07-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartE_app', '0002_remove_student_expiry_date_alter_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodules',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
