# Generated by Django 4.2.1 on 2023-07-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartE_app', '0003_coursemodules_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodules',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
    ]
