# Generated by Django 4.2.1 on 2023-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartE_app', '0004_coursemodules_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
