# Generated by Django 4.2.3 on 2023-07-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartE_app", "0006_remove_coursemodules_files_alter_filesstorage_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="modules_viewed_in_course",
            field=models.JSONField(default=dict),
        ),
    ]
