# Generated by Django 4.2.3 on 2023-07-22 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SmartE_app", "0007_student_modules_viewed_in_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="modules_viewed_in_course",
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SmartE_app.coursemodules",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SmartE_app.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "module")},
            },
        ),
    ]
