# Generated by Django 4.2.3 on 2023-07-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SmartE_app", "0008_remove_student_modules_viewed_in_course_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModuleProgress",
        ),
    ]
