# Generated by Django 4.2.1 on 2023-07-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartE_app', '0009_delete_moduleprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresstracker',
            name='attendance',
        ),
        migrations.AlterField(
            model_name='progresstracker',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartE_app.courses'),
        ),
    ]
