# Generated by Django 4.2.1 on 2023-07-22 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SmartE_app', '0011_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='professors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
