# Generated by Django 4.2.3 on 2023-07-22 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SmartE_app", "0012_alter_courses_professors"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SmartE_app.coursemodules",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SmartE_app.student",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ModuleProgressTracker",
        ),
        migrations.AlterField(
            model_name="progresstracker",
            name="progress",
            field=models.ManyToManyField(to="SmartE_app.moduleprogress"),
        ),
    ]
